# Generated by Django 2.2.7 on 2019-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeARM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallworkers',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
